# Generated by Django 6.0.6 on 2026-07-19 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyewaan',
            name='administrator_validator',
        ),
        migrations.RemoveField(
            model_name='penyewaan',
            name='alasan_penolakan',
        ),
        migrations.RemoveField(
            model_name='penyewaan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='penyewaan',
            name='petugas_pemroses',
        ),
        migrations.AddField(
            model_name='penyewaan',
            name='total_biaya',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='penyewaan',
            name='metode_pembayaran',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='penyewaan',
            name='pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
